# Generated by Django 4.2.7 on 2023-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about_alter_settings_options_alter_slide_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='history_image_1', verbose_name='Первая фотография')),
                ('image_2', models.ImageField(upload_to='history_image_2', verbose_name='Второя фотография')),
                ('descriptions', models.TextField(verbose_name='Описания истории')),
            ],
            options={
                'verbose_name': ('Наша история',),
                'verbose_name_plural': 'Наша история',
            },
        ),
    ]
